language: php

git:
    depth: 2

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - SYMFONY_VERSION="3.4.*"
    - SYMFONY_VERSION="4.3.*"
    - SYMFONY_VERSION="4.4.*"
    - SYMFONY_VERSION="5.0.*"
    - SYMFONY_VERSION="5.1.*"

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - composer validate

install:
    - composer require --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress symfony/symfony:${SYMFONY_VERSION}

script:
    - ./vendor/bin/phpunit --color --testdox tests/