name: "Automated Tests"

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-latest"
    
    strategy:
      matrix:
        dbal-version:
          - "2.12.*"
          - "3.0.*"
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        symfony-version:
          - "3.4.*"
          - "4.4.*"
          - "5.2.*"
          - "5.3.*"

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"

    - name: "Install PHP version from matrix"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"

    - name: "Validate composer.json and composer.lock"
      run: "composer validate"

    - name: "Require Doctrine DBAL and Symfony versions from matrix"
      run: "composer require --ansi --no-interaction --no-progress --no-suggest --optimize-autoloader --prefer-dist doctrine/dbal:${{ matrix.dbal-version }} symfony/symfony:${{ matrix.symfony-version }}"

    - name: "Run PHPUnit"
      run: "vendor/bin/phpunit --colors=always --testdox tests/"
